-- AlterTable
ALTER TABLE "Job" ADD COLUMN "packageReady" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN "packageUrl" TEXT;
ALTER TABLE "Job" ADD COLUMN "packageError" TEXT;
ALTER TABLE "Job" ADD COLUMN "packageJson" JSONB;
ALTER TABLE "Job" ADD COLUMN "voiceoverUrl" TEXT;
ALTER TABLE "Job" ADD COLUMN "voiceoverDurationSec" DOUBLE PRECISION;
ALTER TABLE "Job" ADD COLUMN "imagesOnly" BOOLEAN NOT NULL DEFAULT true;
